import type { FeedEvent, ThreatMatrix } from "./types";
export function scoreBand(value:number):string{ if(value>=8) return "CRITICAL"; if(value>=6) return "HIGH"; if(value>=3) return "ELEVATED"; return "LOW"; }
export function averageConfidence(events:FeedEvent[]):number{ if(!events.length) return 0; return Math.round(events.reduce((s,e)=>s+e.confidence,0)/events.length); }
export function formatThreatOrder(threat:string):number{ const rank:Record<string,number>={CRITICAL:4,HIGH:3,ELEVATED:2,LOW:1}; return rank[threat]||0; }
export function clusterCounts(events:FeedEvent[]){ return { conflict: events.filter(e=>/missile|drone|military|war|strike|defense|navy|air force|ukraine|iran|israel|gaza/i.test(`${e.title} ${e.summary}`)).length, markets: events.filter(e=>/oil|shipping|logistics|tariff|dollar|treasury|inflation|equity|market|energy|trade/i.test(`${e.title} ${e.summary}`)).length, infrastructure: events.filter(e=>/cyber|infrastructure|compute|ai|semiconductor|data|cloud|network|grid/i.test(`${e.title} ${e.summary}`)).length, information: events.filter(e=>/policy|executive|congress|agency|sanction|diplomacy|summit|foreign ministry|white house|senate/i.test(`${e.title} ${e.summary}`)).length }; }
export function buildEscalationModel(matrix:ThreatMatrix, confidence:number):string{ const severe=[matrix.conflict,matrix.markets,matrix.infrastructure,matrix.information].filter(x=>x==="HIGH"||x==="CRITICAL").length; if(matrix.overall==="CRITICAL"||severe>=3) return `Active cross-domain stress. Confidence ${confidence}/100.`; if(matrix.overall==="HIGH"||severe>=2) return `Elevated crossover pressure. Confidence ${confidence}/100.`; if(matrix.overall==="ELEVATED") return `Developing pressure. Confidence ${confidence}/100.`; return `Guarded posture. Confidence ${confidence}/100.`; }
export function buildSitrepBlock(events:FeedEvent[], counts:{conflict:number;markets:number;infrastructure:number;information:number}, matrix:ThreatMatrix):string{ const avg=averageConfidence(events); return `CONFLICT SITREP: ${counts.conflict} items.\nMARKET SITREP: ${counts.markets} items.\nINFRASTRUCTURE SITREP: ${counts.infrastructure} items.\nPOLICY SITREP: ${counts.information} items.\n\nOVERALL SITREP\nThreat posture is assessed at ${matrix.overall}. Average cycle confidence is ${avg}/100.`; }
export function downloadTextFile(filename:string, content:string){ const blob=new Blob([content],{type:"text/plain;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=filename; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }
export function buildPrintHtml(text:string):string{ const escaped=text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); return `<!doctype html><html><head><title>RSR AXION Brief</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#111}pre{white-space:pre-wrap;line-height:1.6;font-size:14px}</style></head><body><h1>RSR AXION Intelligence Brief</h1><pre>${escaped}</pre></body></html>`; }
export function safeLoad<T>(key:string, fallback:T):T{ if(typeof window==="undefined") return fallback; try { const raw=window.localStorage.getItem(key); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } }
export function saveToStorage(key:string, value:unknown){ if(typeof window==="undefined") return; window.localStorage.setItem(key, JSON.stringify(value)); }
